### ISSUE TITLE
Unijoystickle with Joystick switcher

### ISSUE THREAD

**Issue by mwedmark** [ricardoquesada/unijoysticle2#11]
A classical product that is very close to UJ is a Joystick switcher to be able to switch between Port 1 and Port 2, maybe especially for C64. This would be a great addition to the current board. 
This would mean at least one more 9-SUB input male connector and maybe one more button to set UJ in pass-through/Bluetooth mode. By some kind of keypress/switch combination, switching between Port 1 and Port 2 passs-through.
Anything interesting to extend UJ with?

I managed to squeeze in a 9-pin DSUB male for Joystick input and also Route 5 lines (UP/DOWN/RIGHT/LEFT/FIRE) to 5 of the non-used SPI pins on the ESP32. It actually still uses the same size PCB but most components have move. I think it used 54 VIA's in the end currently. I don't know if this would end up violating any old rule you had whne setting up the PCB. This verrsion would probably NOT be easy to hand solder... everything is very tight!

![UJ2+Switcher](https://user-images.githubusercontent.com/2123085/151717483-d26fe6dd-07bb-4bb6-a5e8-fd606fea8b6e.png)
![UJ2+Switcher_3D](https://user-images.githubusercontent.com/2123085/151717485-6c18d2ac-f8ce-48e3-9e87-25fbce7dca4d.png)

**Comment by ricardoquesada** [comment]
Interesting idea.
Although I'm not convinced about the use case.

Switching between port #1 and port #2 is already supported in the Unijoysticle... just pressing the "Home" button in the gamepad does that.

Adding the extra port to support a wired-joystick + a gamepad adds some value I guess. I guess some users might want that.
But I think it will add more confusion... 

But hey, feel free to build them!

**Comment by mwedmark** [comment]
Just to be clear I haven't even built or used any Unijoystickle yet, but I will try it. I guess will build both the original Unijoystickle 2+ and try it out on my C64 Breadbox and also build some of these and try them out. Do you see any problem with adding a pass-through mode for this new port in software?

**Comment by ricardoquesada** [comment]
it depends the amount of code needed.
The firmware is structured in a way that it is easy to create their own platforms.
As an example, the code has 6 "platforms":
 - unijoysticle
 -  mightymiggy
 - arduino
 - nina
 - circuipython
 - pc_debug (used mostly for debugging)

And for me, it is easier if the owners of the different platforms add and maintain their own code.
Adding code for the Unijoysticle that I cannot test is not a good idea.

Also the "unijoysticle" platform at the moment has 3 different modes: unijoysticle 2, unijoysticle 2+ and arana's net unijoysticle...

So, mantainance is something that I worry about.

Are you familiar with coding? If so, perhaps the best is just to fork the project, and make your own changes in the Unijoysticle platform... and if the changes are big, perhaps create your own platform.

**Comment by mwedmark** [comment]
Ok thanks for taking the time and sharing all the info on adding these functions.  I'll give it a try to extend unijoystickle on separate fork and see where that takes me.

Coding should hopefully be ok since that has been my day job and hobby since 30 years back. I've done assembler, C/C++,C#, Basic, Pascal, ADA and others. I've tried platforms as: AVR, ARM/STM32, Propeller, 68000, 6502, DSPs, Z80, x86. I've also been doing FPGAs, creating my own CPUs, Graphics cores, tool chains/compilers. Lately I've been exploring creating/changing/building PCBs to extend my knowledge on that subject.
