### ISSUE TITLE
WIFI/HTML configuration

### ISSUE THREAD

**Issue by mwedmark** [ricardoquesada/unijoysticle2#12]
Has there been any though to adding HTML configuration page or is there a power budget reason to disable WIFI?

**Comment by ricardoquesada** [comment]
power-wise, it will take more current...

But before discussing that, what things would you like to have configured via HTML/WiFi?
Perhaps there are alternative ways to do what you have in mind.

**Comment by mwedmark** [comment]
OK yea I just though to optimize a little bit.. Everything That is switchable using buttons on-board or via buttons on joystick could be made clearer. May even some new good stuff could be added, Autofire and maybe something else..

**Comment by ricardoquesada** [comment]
Yes, for changing the mappings, the plan is to enable a BLE (Bluetooth Low Energy) service, and let users change the mappings via their phones.

BTW: autofire is already supported... but changing the frequency of the autofire is one of the planned features to be added in the BLE configuration.


BLE vs WiFi:
 - less current
 - easier to connect to... no need to setup an AP or things like that.
 - Until recently it was not possible to have both WiFI and Bluetooth ATM, although I think it has been fixed.

**Comment by mwedmark** [comment]
OK BLE sounds like a nice idea. Thank for you input on the idea.
