### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by Nagytalp** [ricardoquesada/unijoysticle2#14]
Hi,

may I use CH340G instead of "C" on 2+ version?
The differece betwwen the two is the "C" model have an built in cryctal oscillator but the "G" doesn't.

And I've stuck on recognise S8050 (Q1,Q2) NPN transistor. I found 6 different tipe  where the collector-emitter voltage is 25 V. But  collector current and the frequency are different.

https://www.tme.eu/hu/en/katalog/?search=s8050&s_field=1000011&s_order=desc

Wich is good for the build?

Thank you for your great work! I'm learning a lot from you.

Best regards,
Csaba.

**Comment by ricardoquesada** [comment]
which schematic are you looking at ?

**Comment by ricardoquesada** [comment]
ah... you said "2+".

So:

a) you cannot use CH340G. Use "B" or "C"
b) regarding S8050, try this one: https://www.tme.eu/hu/en/details/s8050-h-yan/npn-smd-transistors/yangjie-technology/s8050-h/
